apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-jaeger
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: jaeger
    repoURL: https://github.com/chestercodes/homelab-cluster.git
    targetRevision: HEAD
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

