apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps.yaml
- argocd.yaml
- argo-events.yaml
- argo-rollouts.yaml
- argo-workflows.yaml
- cert-manager.yaml
- kube-prometheus-stack.yaml
- loki-stack.yaml
- monitoring.yaml
- jaeger.yaml
- registry.yaml
- registry-ui.yaml
- traefik-ingress.yaml