apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer-staging
  namespace: cert-manager
spec:
  acme:
    email: {{ .Values.acmeEmail }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-issuer-staging-account-key
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.cloudflareEmail }}
          apiTokenSecretRef:
            # Name of the secret created on the other resource
            name: cloudflare-api-token-secret
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer-production
  namespace: cert-manager
spec:
  acme:
    email: {{ .Values.acmeEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-issuer-production-account-key
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.cloudflareEmail }}
          apiTokenSecretRef:
            # Name of the secret created on the other resource
            name: cloudflare-api-token-secret
            key: api-token
---
