apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: pipeline
spec:
  ports:
    - name: http-5000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: docker-registry
    release: registry
  type: ClusterIP
