apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.local`)
      priority: 10
      services:
        - name: "{{ .Release.Name }}-server"
          port: 80
    - kind: Rule
      match: Host(`argocd.local`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: "{{ .Release.Name }}-server"
          port: 80
          scheme: h2c
    - kind: Rule
      match: Host(`argocd.home.arpa`)
      priority: 10
      services:
        - name: "{{ .Release.Name }}-server"
          port: 80
    - kind: Rule
      match: Host(`argocd.home.arpa`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: "{{ .Release.Name }}-server"
          port: 80
          scheme: h2c
  tls:
    certResolver: default
