## Argo CD configuration
## Ref: https://github.com/argoproj/argo-cd
## https://raw.githubusercontent.com/argoproj/argo-helm/main/charts/argo-cd/values.yaml

argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: git
          url: https://github.com/chestercodes/homelab-cluster.git
          passwordSecret:
            name: github-creds
            key: password
          usernameSecret:
            name: github-creds
            key: username
        - type: git
          url: https://github.com/chestercodes/homelab-apps.git
          passwordSecret:
            name: github-creds
            key: password
          usernameSecret:
            name: github-creds
            key: username
        - type: git
          url: https://github.com/chestercodes/homelab-ping.git
          passwordSecret:
            name: github-creds
            key: password
          usernameSecret:
            name: github-creds
            key: username
        - type: git
          url: https://github.com/chestercodes/homelab-maindb.git
          passwordSecret:
            name: github-creds
            key: password
          usernameSecret:
            name: github-creds
            key: username
